"""empty message

Revision ID: 4dae44b2d059
Revises: 
Create Date: 2021-10-15 13:59:45.780846

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4dae44b2d059'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(length=60), nullable=False),
    sa.Column('user_birthdate', sa.DateTime(), nullable=False),
    sa.Column('user_cpf', sa.String(), nullable=False),
    sa.Column('user_city', sa.String(), nullable=False),
    sa.Column('is_owner', sa.Boolean(), nullable=True),
    sa.Column('user_phone', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_modified', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_cpf')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
