"""empty message

Revision ID: 8a9474fe5698
Revises: 4dae44b2d059
Create Date: 2021-10-17 17:53:18.275110

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a9474fe5698'
down_revision = '4dae44b2d059'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pet_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pet_name', sa.String(length=60), nullable=False),
    sa.Column('pet_birthdate', sa.String(), nullable=False),
    sa.Column('pet_description', sa.String(length=155), nullable=False),
    sa.Column('pet_localization', sa.String(length=60), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pet_description')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pet_model')
    # ### end Alembic commands ###
